version: '3'
services:
  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      
  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    restart: unless-stopped

  backend:
    build: ./backend    
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped